server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
    hostname: "localhost"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka/

#management:
#  endpoint:
#    routes:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#Data base

spring:
  application:
    name: Authentication Service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect