kind: Service
apiVersion: v1
metadata:
  name: bank-service
spec:
  selector:
    app: bank-service
  ports:
    - protocol: TCP
      port: 8092
      nodePort: 30803
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
spec:
  selector:
    matchLabels:
      app: bank-service
  replicas: 1
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
        - name: bank-service
          image: endagegnehu/sa-ecommerce-proj-bank_app
          imagePullPolicy: Always
          ports:
            - containerPort: 8092