kind: Service
apiVersion: v1
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8084
      nodePort: 30503
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  selector:
    matchLabels:
      app: order-service
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: endagegnehu/sa-ecommerce-proj-order_app
          imagePullPolicy: Always
          ports:
            - containerPort: 8084