kind: Service
apiVersion: v1
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 8087
      nodePort: 30603
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  selector:
    matchLabels:
      app: payment-service
  replicas: 1
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: endagegnehu/sa-ecommerce-proj-payment_app
          imagePullPolicy: Always
          ports:
            - containerPort: 8087