spring:
  application:
    name: configserver

  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/abdibedaso/spring-config-server-demo-config-2.git
          clone-on-start: true
        bootstrap: true
      discovery:
        enabled: true
      fail-fast: true
      retry:
        initial-interval: 1000

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8888
