spring:
  application:
    name: configserver

  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/abdibedaso/spring-config-server-demo-config-2.git
          clone-on-start: true
        bootstrap: true
      discovery:
        enabled: true
      fail-fast: true
      retry:
        initial-interval: 1000

management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.19.141.91:8761/eureka
  instance:
    preferIpAddress: true
    ip-address: 172.19.141.91

server:
  port: 8888
